// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface hasPrecenseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.hasPrecense)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool presence = 1;</code>
   * @return The presence.
   */
  boolean getPresence();
}
