// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_hasPrecense_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_hasPrecense_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\"\036\n\016RequestMes" +
      "sage\022\014\n\004text\030\001 \001(\t\"\037\n\017ResponseMessage\022\014\n" +
      "\004text\030\001 \001(\t\"\037\n\013hasPrecense\022\020\n\010presence\030\001" +
      " \001(\0102\340\001\n\010Service2\022G\n\016check_presence\022\030.se" +
      "rvice2.RequestMessage\032\031.service2.Respons" +
      "eMessage\"\000\022D\n\016turn_lights_on\022\025.service2." +
      "hasPrecense\032\031.service2.ResponseMessage\"\000" +
      "\022E\n\017turn_lights_off\022\025.service2.hasPrecen" +
      "se\032\031.service2.ResponseMessage\"\000B\035\n\013ds.se" +
      "rvice2B\014Service2ImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_service2_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_RequestMessage_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service2_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_ResponseMessage_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service2_hasPrecense_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_hasPrecense_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_hasPrecense_descriptor,
        new java.lang.String[] { "Presence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
